import React, { useState } from "react";

export default function ExportModal({ paper, summaryData, graph, onClose }) {
  const [copiedFormat, setCopiedFormat] = useState(null);

  if (!paper) return null;

  const multi = summaryData?.multiview || summaryData || {};
  const plainText = multi.plain_language || summaryData?.summary || "";
  const clinicalText = multi.clinical_summary || summaryData?.summary || "";
  const pico = multi.pico || {};
  const sections = multi.structured_sections || {};
  const highlights = multi.key_highlights || [];

  // Generate Markdown Brief
  const markdownContent = `# Research Brief: ${paper.title}

## TL;DR
${multi.tldr || plainText.slice(0, 200)}

---

## 1. Executive Plain-Language Summary
${plainText}

---

## 2. Clinical & Pharmacological Deep Dive
${clinicalText}

### PICO Parameters
- **Population (P)**: ${pico.population || "Clinical patient cohort"}
- **Intervention (I)**: ${pico.intervention || "Investigational therapeutic approach"}
- **Comparator (C)**: ${pico.comparator || "Standard of care or placebo baseline"}
- **Outcomes (O)**: ${pico.primary_outcomes || "Clinical response and survival metrics"}

---

## 3. Structured Sectional Synthesis
### Background & Objectives
${sections.background || "N/A"}

### Methodology & Trial Design
${sections.methodology || "N/A"}

### Key Findings & Statistical Endpoints
${sections.findings || "N/A"}

### Clinical Implications & Conclusions
${sections.conclusion || "N/A"}

---

## 4. Key Quantitative Takeaways
${highlights.map((h, i) => `${i + 1}. ${h}`).join("\n")}

---
*Generated by BioLens 2.0 (Biomedical Intelligence Platform)*
`;

  // Formats
  const citations = {
    bibtex: `@article{biolens_${paper.id || "paper"},
  title = {${paper.title}},
  journal = {Biomedical Research Intelligence Brief},
  year = {${new Date().getFullYear()}},
  note = {Synthesized via BioLens 2.0}
}`,
    apa: `BioLens Research Intelligence. (${new Date().getFullYear()}). Research Synthesis: ${paper.title}. BioLens Platform.`,
    nature: `BioLens. Research synthesis of ${paper.title}. BioLens Intelligence (2026).`,
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `BioLens_Brief_${(paper.title || "paper").slice(0, 30).replace(/\s+/g, "_")}.md`;
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  const handleDownloadJSON = () => {
    const payload = {
      paper_title: paper.title,
      synthesized_at: new Date().toISOString(),
      summary: multi,
      knowledge_graph: graph,
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `BioLens_Data_${(paper.title || "paper").slice(0, 30).replace(/\s+/g, "_")}.json`;
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  const handleCopyCitation = (formatKey, text) => {
    navigator.clipboard.writeText(text);
    setCopiedFormat(formatKey);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="export-modal-sheet" onClick={(e) => e.stopPropagation()}>
        <div className="export-modal-header">
          <div>
            <h3>Export Research Brief & Citations</h3>
            <p>{paper.title}</p>
          </div>
          <button className="close-btn" onClick={onClose}>
            ✕
          </button>
        </div>

        <div className="export-options-grid">
          {/* Markdown Download */}
          <div className="export-card">
            <div className="export-icon">📄</div>
            <h4>Markdown Research Brief</h4>
            <p>Complete multi-perspective brief, PICO matrix, and sectional breakdown in formatted Markdown.</p>
            <button className="export-btn-primary" onClick={handleDownloadMarkdown}>
              ⬇ Download .MD
            </button>
          </div>

          {/* JSON Dataset Download */}
          <div className="export-card">
            <div className="export-icon">🧬</div>
            <h4>Full Research Dataset (JSON)</h4>
            <p>Raw JSON containing structured summary, entity classifications, and knowledge graph nodes/edges.</p>
            <button className="export-btn-secondary" onClick={handleDownloadJSON}>
              ⬇ Download .JSON
            </button>
          </div>
        </div>

        {/* Academic Citation Generator */}
        <div className="citation-generator-section">
          <h4>Formatted Academic Citations</h4>
          <div className="citation-tabs-list">
            {Object.entries(citations).map(([formatKey, citationText]) => (
              <div key={formatKey} className="citation-row">
                <div className="citation-info">
                  <span className="citation-format-tag">{formatKey.toUpperCase()}</span>
                  <code>{citationText}</code>
                </div>
                <button
                  className="copy-citation-btn"
                  onClick={() => handleCopyCitation(formatKey, citationText)}
                >
                  {copiedFormat === formatKey ? "✓ Copied!" : "Copy"}
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
